apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: my-svcnew.my-namespace
spec:
  groups:
  - system:authenticated
  request: "base64"
  usages:
  - digital signature
  - key encipherment
  - server auth
